/* Mahanadi Resort — site content. Generated by admin.html.
   Upload this file to your host (replace the old config.js). */
window.SITE_CONFIG = {
  "name": "Mahanadi",
  "brandLine": "Riverside Resort",
  "heroTag": "On the banks of the Mahanadi",
  "heroTitle": "Mahanadi Resort",
  "heroLede": "A riverside destination in Odisha for weddings, receptions, birthdays and every celebration worth remembering — where the river's calm meets a resort built for once-in-a-lifetime days.",
  "phone": "+919853909972",
  "phoneDisplay": "+91 98539 09972",
  "email": "hello@mahanadiresort.in",
  "address": "Mahanadi Riverfront Estate, Odisha, India",
  "hours": "Every day · 9:00 AM – 9:00 PM",
  "mapQuery": "Mahanadi Resort Odisha",
  "offer": {
    "show": true,
    "text": "✦ Monsoon special — 15% off weekday weddings booked this month ✦"
  },
  "price": {
    "roomPerNight": 3500,
    "mandap": 75000,
    "foodVeg": 450,
    "foodNonVeg": 650,
    "foodPerPlate": 550,
    "flower": 45000,
    "photo": 35000,
    "dj": 25000,
    "stage": 30000,
    "cleaning": 8000,
    "defaultRooms": 4,
    "defaultPlates": 150
  },
  "images": {
    "rooms": "rooms.jpg",
    "mandap": "mandap.jpg",
    "dining": ""
  },
  "gallery": [
    {
      "url": "mandap.jpg",
      "caption": "Wedding Mandap at Dusk",
      "category": "Wedding"
    },
    {
      "url": "rooms.jpg",
      "caption": "The Villa at Twilight",
      "category": "Rooms"
    },
    {
      "url": "garden.jpg",
      "caption": "Lantern Garden Swing",
      "category": "Décor"
    }
  ],
  "bookedDates": [
    "2026-08-01",
    "2026-08-15",
    "2026-08-18",
    "2026-08-19",
  ],
  "reservedDates": [
    "2026-08-09",
    "2026-08-10",
    "2026-08-11"
  ]
};
